# tested for
#   MacOS Catalina
#       Apple clang version 12.0.0 (clang-1200.0.32.29)
#       GNU Make 3.81
#
# build bin file:
#       cd src
#       make

CC=gcc

hack-exec: main.c lib/argument.c lib/callback.c
	$(CC) -o ../bin/hack-exec main.c lib/argument.c lib/callback.c